# Spring properties
spring:
  application:
     name: portal-api  # Service registers under this name
# jdbc 종류 (postgresql, mysql)
  jdbc: postgresql
#  jdbc: mysql

# HTTP Server
server:
  port: ${PORT:2222}   # HTTP (Tomcat) port

# CloudFoundry API Url
cloudfoundry:
  cc:
    api:
      url: https://api.115.68.46.30.xip.io
      uaaUrl: https://uaa.115.68.46.30.xip.io
  # CloudFoundry Login information
  user:
    admin:
      username: admin
      password: admin
    uaaClient:
      clientId: login
      clientSecret: admin
      adminClientId: admin
      adminClientSecret: admin
      loginClientId: login
      loginClientSecret: admin
      skipSSLValidation: true
  authorization: cf-Authorization

abacus:
  url: http://paasta-usage-reporting.115.68.46.30.xip.io/v1

---
spring:
  profiles: local
  security:
    username: admin
    password: openpaasta
  datasource:
    cc:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5524/ccdb
      username: ccadmin
      password: admin
    portal:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5524/portaldb
      username: portaladmin
      password: admin
      mysql:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/portaldb?autoReconnect=true&useUnicode=true&characterEncoding=utf8
        username: portaladmin
        password: admin
    uaa:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5524/uaadb
      username: uaaadmin
      password: admin
  glusterfs:
    tenantName: paasta-portal
    username: paasta-portal
    password: paasta
    authUrl: http://localhost:5000/v2.0
    container: portal-container
  mail:
    smtp:
      host: smtp.gmail.com
      port: 465
      username: PaaS-TA 관리자
      password: openpasta!
      userEmail: openpasta@gmail.com
      properties:
        auth: true
        starttls:
          enable: true
          required: truie
        maximumTotalQps: 90
        authUrl: http://localhost:8080
        imgUrl: http://52.201.48.51:8080/v1/KEY_84586dfdc15e4f8b9c2a8e8090ed9810/portal-container/65bdc7f43e11433b8f17683f96c7e626.png
        sFile: emailTemplate.html
        subject: PaaS-TA User Potal 인증메일(Local)
        contextUrl: user/authUser
multipart:
  maxFileSize: 1000Mb
  maxRequestSize: 1000Mb
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2221/eureka/
logging:
  level:
    org.openpaas.paasta.portal.api.mapper: DEBUG
---
spring:
  profiles: dev
  security:
    username: admin
    password: openpaasta
  datasource:
    cc:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/ccdb
      username: ccadmin
      password: admin
    portal:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/portaldb
      username: portaladmin
      password: admin
    uaa:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/uaadb
      username: uaaadmin
      password: admin
  glusterfs:
    tenantName: paasta-portal
    username: paasta-portal
    password: paasta
    authUrl: http://10.30.131.12:5000/v2.0
    container: portal-container
  mail:
    smtp:
      host: smtp.gmail.com
      port: 465
      username: PaaS-TA 관리자
      password: openpasta!
      userEmail: openpasta@gmail.com
      properties:
        auth: true
        starttls:
          enable: true
          required: truie
        maximumTotalQps: 90
        authUrl: http://portal-web-user-dev.115.68.46.30.xip.io
        imgUrl: http://52.201.48.51:8080/v1/KEY_84586dfdc15e4f8b9c2a8e8090ed9810/portal-container/65bdc7f43e11433b8f17683f96c7e626.png
        sFile: emailTemplate.html
        subject: PaaS-TA User Potal 인증메일
        contextUrl: user/authUser
multipart:
  maxFileSize: 1000Mb
  maxRequestSize: 1000Mb
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.portal-eureka-service.credentials.uri:https://portal-registration-dev.115.68.46.30.xip.io}/eureka/
---
spring:
  profiles: stg
  security:
    username: admin
    password: openpaasta
  datasource:
    cc:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/ccdb
      username: ccadmin
      password: admin
    portal:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/portaldb
      username: portaladmin
      password: admin
    uaa:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/uaadb
      username: uaaadmin
      password: admin
  glusterfs:
    tenantName: paasta-portal
    username: paasta-portal
    password: paasta
    authUrl: http://10.30.131.12:5000/v2.0
    container: portal-container
  mail:
    smtp:
      host: smtp.gmail.com
      port: 465
      username: PaaS-TA 관리자
      password: openpasta!
      userEmail: openpasta@gmail.com
      properties:
        auth: true
        starttls:
          enable: true
          required: truie
        maximumTotalQps: 90
        authUrl: http://portal-web-user-stg.115.68.46.30.xip.io
        imgUrl: http://52.201.48.51:8080/v1/KEY_84586dfdc15e4f8b9c2a8e8090ed9810/portal-container/65bdc7f43e11433b8f17683f96c7e626.png
        sFile: emailTemplate.html
        subject: PaaS-TA User Potal 인증메일
        contextUrl: user/authUser
multipart:
  maxFileSize: 1000Mb
  maxRequestSize: 1000Mb
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.portal-eureka-service.credentials.uri}/eureka/
---
spring:
  profiles: prd
  security:
    username: admin
    password: openpaasta
  datasource:
    cc:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/ccdb
      username: ccadmin
      password: admin
    portal:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/portaldb
      username: portaladmin
      password: admin
    uaa:
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://10.30.110.42:5524/uaadb
      username: uaaadmin
      password: admin
  glusterfs:
    tenantName: paasta-portal
    username: paasta-portal
    password: paasta
    authUrl: http://10.30.131.12:5000/v2.0
    container: portal-container
  mail:
    smtp:
      host: smtp.gmail.com
      port: 465
      username: PaaS-TA 관리자
      password: openpasta!
      userEmail: openpasta@gmail.com
      properties:
        auth: true
        starttls:
          enable: true
          required: truie
        maximumTotalQps: 90
        authUrl: http://portal-web-user-prd.115.68.46.30.xip.io
        imgUrl: http://52.201.48.51:8080/v1/KEY_84586dfdc15e4f8b9c2a8e8090ed9810/portal-container/65bdc7f43e11433b8f17683f96c7e626.png
        sFile: emailTemplate.html
        subject: PaaS-TA User Potal 인증메일
        contextUrl: user/authUser
multipart:
  maxFileSize: 1000Mb
  maxRequestSize: 1000Mb
eureka:
  instance:
    hostname: ${vcap.application.uris[0]}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.portal-eureka-service.credentials.uri}/eureka/