spring:
  application:
    name: portal-auto-scaling  # Identify this application
  redis:
    host: ${vcap.services.portal-redis-session.credentials.host:localhost}
    password: ${vcap.services.portal-redis-session.credentials.password:53728b4d-8196-488d-b162-20c4a44e045d}
    port: ${vcap.services.portal-redis-session.credentials.port:43142}
    timeout: 2100

# HTTP Server
server:
  port: ${PORT:8070}   # HTTP (Tomcat) port

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.portal-eureka-service.credentials.uri:http://127.0.0.1:2221}/eureka/
  instance:
    hostname: ${vcap.application.uris[0]:localhost}

# paasta
paasta:
  portal:
    api:
      authorization:
        base64: Basic YWRtaW46b3BlbnBhYXN0YQ==
      url: http://PORTAL-API
      monitor: http://115.68.46.190:9999

# CloudFoundry API Url
cloudfoundry:
  user:
    admin:
      username: admin
      password: xxxxx

ribbon:
  eureka:
    enabled: true
  ConnectTimeout: 30000
  ReadTimeout: 30000

---
# Spring properties
spring:
  profiles: local
  application:
    name: portal-auto-scaling  # Identify this application
  redis:
    host: ${vcap.services.portal-redis-session.credentials.host:localhost}
    password: ${vcap.services.portal-redis-session.credentials.password:4333c2c0-4f51-433d-a5c3-ede30af0c63f}
    port: ${vcap.services.portal-redis-session.credentials.port:33777}
    timeout: 2100

---
# Spring properties
spring:
  profiles: dev
  application:
    name: portal-auto-scaling  # Identify this application
  redis:
    host: ${vcap.services.portal-redis-session.credentials.host:localhost}
    password: ${vcap.services.portal-redis-session.credentials.password:4333c2c0-4f51-433d-a5c3-ede30af0c63f}
    port: ${vcap.services.portal-redis-session.credentials.port:33777}
    timeout: 2100

---
spring:
  profiles: stg
  application:
    name: portal-auto-scaling  # Identify this application
  redis:
    host: ${vcap.services.portal-redis-session.credentials.host:localhost}
    password: ${vcap.services.portal-redis-session.credentials.password:4333c2c0-4f51-433d-a5c3-ede30af0c63f}
    port: ${vcap.services.portal-redis-session.credentials.port:33777}
    timeout: 2100

---
spring:
  profiles: prd
  application:
    name: portal-auto-scaling  # Identify this application
  redis:
    host: ${vcap.services.portal-redis-session.credentials.host:localhost}
    password: ${vcap.services.portal-redis-session.credentials.password:4333c2c0-4f51-433d-a5c3-ede30af0c63f}
    port: ${vcap.services.portal-redis-session.credentials.port:33777}
    timeout: 2100


